=== A158Coke/Lenguaje-de-marcas/XML/XML Schema/actividad12/actividad12.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="CD_Oferta">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="CD" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Título" type="xs:string" />
                            <xs:element name="Aritista" type="xs:string" />
                            <xs:element name="País" type="xs:string" />
                            <xs:element name="Compañía_discográfica" type="xs:string" />
                            <xs:element name="Precio" type="xs:string" />
                            <xs:element name="Año_de_publicación" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== A158Coke/Lenguaje-de-marcas/XML/XSD y  XSL/actividad12/actividad12.xml
<?xml version="1.0" encoding="UTF-8"?>
<CD_Oferta xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="actividad12.xsd">
        <CD>
            <Título>Still got the blues</Título>
            <Aritista>Garry Moore</Aritista>
            <País>UK</País>
            <Compañía_discográfica>Virgin records</Compañía_discográfica>
            <Precio>10.20</Precio>
            <Año_de_publicación>1990</Año_de_publicación>
        </CD>

        <CD>
            <Título>One night only</Título>
            <Aritista>Bee Gees</Aritista>
            <País>UK</País>
            <Compañía_discográfica>Polydor</Compañía_discográfica>
            <Precio>10.90</Precio>
            <Año_de_publicación>1998</Año_de_publicación>
        </CD>

        <CD>
            <Título>When a man loves a woman</Título>
            <Aritista>Percy Sledge</Aritista>
            <País>USA</País>
            <Compañía_discográfica>Atlantic</Compañía_discográfica>
            <Precio>8.70</Precio>
            <Año_de_publicación>1987</Año_de_publicación>
        </CD>

        <CD>
            <Título>Big Willie style</Título>
            <Aritista>Will Smith</Aritista>
            <País>USA</País>
            <Compañía_discográfica>Columbia</Compañía_discográfica>
            <Precio>9.90</Precio>
            <Año_de_publicación>1997</Año_de_publicación>
        </CD>

        <CD>
            <Título>La cación de Juan Perro</Título>
            <Aritista>Radio Futura</Aritista>
            <País>España</País>
            <Compañía_discográfica>Sony Music-Ariola</Compañía_discográfica>
            <Precio>9.90</Precio>
            <Año_de_publicación>1987</Año_de_publicación>
        </CD>

        <CD>
            <Título>The dock of the bay</Título>
            <Aritista>Otis Redding</Aritista>
            <País>USA</País>
            <Compañía_discográfica>Atlantic</Compañía_discográfica>
            <Precio>7.90</Precio>
            <Año_de_publicación>1987</Año_de_publicación>
        </CD>
</CD_Oferta>
