=== A158Coke/Lenguaje-de-marcas/XML/XML Schema/actividad13/actividad13.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="mensaje">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="remite">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="email" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="destinatori0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="email" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="asunto" type="xs:string" />
                <xs:element name="texto">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="parrafo" maxOccurs="unbounded" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== A158Coke/Lenguaje-de-marcas/XML/XML Schema/actividad13/actividad13.xml
<?xml  version="1.0" encoding="UTF-8"?>
<mensaje xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="actividad13.xsd"  >
    <remite>
        <nombre>Alfredo Reino</nombre>
        <email>alf@ibium.com</email>
    </remite>
    <destinatori0>
        <nombre>Bill Clindon</nombre>
        <email>president@whitehouse.gov</email>
    </destinatori0>
    <asunto>Hola Bill</asunto>
    <texto>
        <parrafo>¿Hola qué tal?</parrafo>
        <parrafo>...</parrafo>

    </texto>
   
</mensaje>
